export const TriviaActionTypes = {
  CATEGORIES_LOADING: 'CATEGORIES_LOADING',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_ENTRY_CATEGORY: 'SET_ENTRY_CATEGORY',
  QUESTIONS_LOADING: 'QUESTIONS_LOADING',
  SET_QUESTIONS: 'SET_QUESTIONS',
  UPDATE_SCORE: 'UPDATE_SCORE',
  SET_ENTRY_QUESTION: 'SET_ENTRY_QUESTION',
  SET_ENTRY_QUESTION_INDEX: 'SET_ENTRY_QUESTION_INDEX',
  SET_ANSWERS: 'SET_ANSWERS'
};